version: '3.8'
services:
  eureka-server:
    image: grzesiekoladele/eureka-service
    container_name: eureka-service
    ports:
      - '8761:8761'
    restart: always
    networks:
      - moto-microservices

volumes:
  moto-db:
networks:
  moto-microservices:
    driver: bridge